2013/11/21 19:13:41 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:13:53 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:16:39 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:17:02 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:17:50 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:18:39 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:19:54 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:21:07 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(35): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (35)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:22:23 [error] [php] include(Settings.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\Controller.php(16): spl_autoload_call()
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(281): SiteController->init()
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\Controller.php (16)
in P:\home\blog.rt\www\index.php (13)
2013/11/21 19:22:51 [error] [php] include(Settings.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\Controller.php(16): spl_autoload_call()
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(281): SiteController->init()
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\Controller.php (16)
in P:\home\blog.rt\www\index.php (13)
2013/11/21 19:23:13 [error] [php] include(Users.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(15): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (15)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:23:24 [error] [php] include(Users.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(15): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (15)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:23:30 [error] [php] include(Settings.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\Controller.php(16): spl_autoload_call()
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(281): SiteController->init()
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\Controller.php (16)
in P:\home\blog.rt\www\index.php (13)
2013/11/21 19:25:39 [error] [php] include(Settings.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\Controller.php(16): spl_autoload_call()
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(281): SiteController->init()
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\Controller.php (16)
in P:\home\blog.rt\www\index.php (13)
2013/11/21 19:25:42 [error] [php] include(Settings.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\Controller.php(16): spl_autoload_call()
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(281): SiteController->init()
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\Controller.php (16)
in P:\home\blog.rt\www\index.php (13)
2013/11/21 19:26:15 [error] [php] include(Users.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\UserIdentity.php(15): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 P:\home\blog.rt\YiiRoot\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 P:\home\blog.rt\YiiRoot\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 P:\home\blog.rt\YiiRoot\framework\base\CModel.php(159): CInlineValidator->validate()
#5 P:\home\blog.rt\www\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#9 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#11 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in P:\home\blog.rt\www\protected\components\UserIdentity.php (15)
in P:\home\blog.rt\www\protected\models\LoginForm.php (52)
in P:\home\blog.rt\www\protected\controllers\SiteController.php (94)
2013/11/21 19:27:03 [error] [exception.CException] exception 'CException' with message 'Unknown authorization item "3".' in P:\home\blog.rt\YiiRoot\framework\web\auth\CPhpAuthManager.php:179
Stack trace:
#0 P:\home\blog.rt\www\protected\components\PhpAuthManager.php(16): CPhpAuthManager->assign('3', '1')
#1 P:\home\blog.rt\YiiRoot\framework\base\CModule.php(387): PhpAuthManager->init()
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(185): CModule->getComponent('authManager')
#3 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#4 P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php(346): CWebUser->checkAccess('2')
#5 P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php(284): CAccessRule->isRoleMatched(Object(WebUser))
#6 P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php(138): CAccessRule->isUserAllowed(Object(WebUser), Object(IndexController), Object(CInlineAction), '127.0.0.1', 'GET')
#7 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#8 P:\home\blog.rt\YiiRoot\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#9 P:\home\blog.rt\YiiRoot\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#10 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 P:\home\blog.rt\YiiRoot\framework\web\CController.php(291): CFilterChain->run()
#12 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('')
#14 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#15 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 P:\home\blog.rt\www\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/index.php?r=admin
HTTP_REFERER=http://blog.rt/index.php?r=site/login
---
2013/11/21 19:29:40 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), 'You are not aut...')
#1 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 P:\home\blog.rt\YiiRoot\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 P:\home\blog.rt\YiiRoot\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 P:\home\blog.rt\YiiRoot\framework\web\CController.php(291): CFilterChain->run()
#6 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('')
#8 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#9 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 P:\home\blog.rt\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin
HTTP_REFERER=http://blog.rt/index.php?r=site/login
---
2013/11/21 19:29:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), 'You are not aut...')
#1 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 P:\home\blog.rt\YiiRoot\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 P:\home\blog.rt\YiiRoot\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 P:\home\blog.rt\YiiRoot\framework\web\CController.php(291): CFilterChain->run()
#6 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('')
#8 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#9 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 P:\home\blog.rt\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin
---
2013/11/21 20:01:40 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '?? ?????? ?????...')
#1 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 P:\home\blog.rt\YiiRoot\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 P:\home\blog.rt\YiiRoot\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 P:\home\blog.rt\YiiRoot\framework\web\CController.php(291): CFilterChain->run()
#6 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('')
#8 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#9 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 P:\home\blog.rt\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin
---
2013/11/21 20:03:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '?? ?????? ?????...')
#1 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 P:\home\blog.rt\YiiRoot\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 P:\home\blog.rt\YiiRoot\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 P:\home\blog.rt\YiiRoot\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 P:\home\blog.rt\YiiRoot\framework\web\CController.php(291): CFilterChain->run()
#6 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('')
#8 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#9 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 P:\home\blog.rt\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin
---
2013/11/21 21:39:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "login".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/?r=login
---
2013/11/21 21:50:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "login".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('login')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('login')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://blog.rt/index.php
---
2013/11/21 23:56:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "users".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=users
---
2013/11/21 23:56:51 [error] [php] include(Users.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\WebUser.php(22): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\components\WebUser.php(14): WebUser->getModel()
#2 P:\home\blog.rt\YiiRoot\framework\base\CComponent.php(111): WebUser->getRole()
#3 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(146): WebUser->__get()
#4 P:\home\blog.rt\www\protected\components\PhpAuthManager.php(16): WebUser->__get()
#5 P:\home\blog.rt\YiiRoot\framework\base\CModule.php(387): PhpAuthManager->init()
#6 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(185): CWebApplication->getComponent()
#7 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#8 P:\home\blog.rt\www\protected\views\layouts\main.php(62): WebUser->checkAccess()
#9 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#10 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#11 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#12 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#13 P:\home\blog.rt\YiiRoot\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#14 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(206): CContentDecorator->run()
#15 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(300): SiteController->endWidget()
#16 P:\home\blog.rt\www\protected\views\layouts\column2.php(23): SiteController->endContent()
#17 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#18 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#19 P:\home\blog.rt\YiiRoot\framework\web\CController.php(784): SiteController->renderFile()
#20 P:\home\blog.rt\www\protected\controllers\SiteController.php(53): SiteController->render()
#21 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#22 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#23 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#24 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#25 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#26 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#27 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/img/favicon.ico
in P:\home\blog.rt\www\protected\components\WebUser.php (22)
in P:\home\blog.rt\www\protected\components\WebUser.php (14)
in P:\home\blog.rt\www\protected\components\PhpAuthManager.php (16)
2013/11/21 23:56:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "users".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=users
---
2013/11/21 23:56:52 [error] [php] include(Users.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\WebUser.php(22): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\components\WebUser.php(14): WebUser->getModel()
#2 P:\home\blog.rt\YiiRoot\framework\base\CComponent.php(111): WebUser->getRole()
#3 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(146): WebUser->__get()
#4 P:\home\blog.rt\www\protected\components\PhpAuthManager.php(16): WebUser->__get()
#5 P:\home\blog.rt\YiiRoot\framework\base\CModule.php(387): PhpAuthManager->init()
#6 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(185): CWebApplication->getComponent()
#7 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#8 P:\home\blog.rt\www\protected\views\layouts\main.php(62): WebUser->checkAccess()
#9 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#10 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#11 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#12 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#13 P:\home\blog.rt\YiiRoot\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#14 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(206): CContentDecorator->run()
#15 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(300): SiteController->endWidget()
#16 P:\home\blog.rt\www\protected\views\layouts\column2.php(23): SiteController->endContent()
#17 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#18 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#19 P:\home\blog.rt\YiiRoot\framework\web\CController.php(784): SiteController->renderFile()
#20 P:\home\blog.rt\www\protected\controllers\SiteController.php(53): SiteController->render()
#21 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#22 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#23 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#24 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#25 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#26 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#27 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/img/favicon.ico
in P:\home\blog.rt\www\protected\components\WebUser.php (22)
in P:\home\blog.rt\www\protected\components\WebUser.php (14)
in P:\home\blog.rt\www\protected\components\PhpAuthManager.php (16)
2013/11/21 23:57:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "users".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=users
---
2013/11/21 23:57:04 [error] [php] include(Users.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\WebUser.php(22): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\components\WebUser.php(14): WebUser->getModel()
#2 P:\home\blog.rt\YiiRoot\framework\base\CComponent.php(111): WebUser->getRole()
#3 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(146): WebUser->__get()
#4 P:\home\blog.rt\www\protected\components\PhpAuthManager.php(16): WebUser->__get()
#5 P:\home\blog.rt\YiiRoot\framework\base\CModule.php(387): PhpAuthManager->init()
#6 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(185): CWebApplication->getComponent()
#7 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#8 P:\home\blog.rt\www\protected\views\layouts\main.php(62): WebUser->checkAccess()
#9 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#10 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#11 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#12 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#13 P:\home\blog.rt\YiiRoot\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#14 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(206): CContentDecorator->run()
#15 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(300): SiteController->endWidget()
#16 P:\home\blog.rt\www\protected\views\layouts\column2.php(23): SiteController->endContent()
#17 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#18 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#19 P:\home\blog.rt\YiiRoot\framework\web\CController.php(784): SiteController->renderFile()
#20 P:\home\blog.rt\www\protected\controllers\SiteController.php(53): SiteController->render()
#21 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#22 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#23 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#24 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#25 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#26 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#27 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/img/favicon.ico
in P:\home\blog.rt\www\protected\components\WebUser.php (22)
in P:\home\blog.rt\www\protected\components\WebUser.php (14)
in P:\home\blog.rt\www\protected\components\PhpAuthManager.php (16)
2013/11/21 23:57:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "users".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=users
---
2013/11/21 23:57:05 [error] [php] include(Users.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (P:\home\blog.rt\YiiRoot\framework\YiiBase.php:427)
Stack trace:
#0 P:\home\blog.rt\www\protected\components\WebUser.php(22): spl_autoload_call()
#1 P:\home\blog.rt\www\protected\components\WebUser.php(14): WebUser->getModel()
#2 P:\home\blog.rt\YiiRoot\framework\base\CComponent.php(111): WebUser->getRole()
#3 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(146): WebUser->__get()
#4 P:\home\blog.rt\www\protected\components\PhpAuthManager.php(16): WebUser->__get()
#5 P:\home\blog.rt\YiiRoot\framework\base\CModule.php(387): PhpAuthManager->init()
#6 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(185): CWebApplication->getComponent()
#7 P:\home\blog.rt\YiiRoot\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#8 P:\home\blog.rt\www\protected\views\layouts\main.php(62): WebUser->checkAccess()
#9 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#10 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#11 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#12 P:\home\blog.rt\YiiRoot\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#13 P:\home\blog.rt\YiiRoot\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#14 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(206): CContentDecorator->run()
#15 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(300): SiteController->endWidget()
#16 P:\home\blog.rt\www\protected\views\layouts\column2.php(23): SiteController->endContent()
#17 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(126): require()
#18 P:\home\blog.rt\YiiRoot\framework\web\CBaseController.php(95): SiteController->renderInternal()
#19 P:\home\blog.rt\YiiRoot\framework\web\CController.php(784): SiteController->renderFile()
#20 P:\home\blog.rt\www\protected\controllers\SiteController.php(53): SiteController->render()
#21 P:\home\blog.rt\YiiRoot\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#22 P:\home\blog.rt\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams()
#23 P:\home\blog.rt\YiiRoot\framework\web\CController.php(286): SiteController->runAction()
#24 P:\home\blog.rt\YiiRoot\framework\web\CController.php(265): SiteController->runActionWithFilters()
#25 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): SiteController->run()
#26 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController()
#27 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 P:\home\blog.rt\www\index.php(13): CWebApplication->run()
REQUEST_URI=/img/favicon.ico
in P:\home\blog.rt\www\protected\components\WebUser.php (22)
in P:\home\blog.rt\www\protected\components\WebUser.php (14)
in P:\home\blog.rt\www\protected\components\PhpAuthManager.php (16)
2013/11/21 23:57:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "users".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=users
---
2013/11/22 00:02:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "login".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('login')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('login')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://blog.rt/index.php
---
2013/11/22 00:02:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "login".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('login')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('login')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://blog.rt/index.php?r=site/login
---
2013/11/22 00:02:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "login".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('login')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('login')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://blog.rt/index.php?r=site/login
---
2013/11/22 00:48:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "admik".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('admik')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=admik
---
2013/11/22 01:07:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "img/favicon.ico".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('img/favicon.ico')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/img/favicon.ico
---
2013/11/22 01:08:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:08:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:08:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:08:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:08:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:09:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:10:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:10:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:10:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:10:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:10:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:11:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:11:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:11:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:11:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:11:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:13:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:13:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:13:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:13:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:13:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:14:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:14:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:14:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:14:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:14:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:15:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:16:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:17:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:18:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:19:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:19:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:19:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:19:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:19:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:19:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "favicon.ico".' in P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 P:\home\blog.rt\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/11/22 01:20:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:20:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:20:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:20:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:20:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:21:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "js".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('js')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('js')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/functio...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/js/functions.js
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/russia...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/russia.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/USA.pn...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/USA.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:30:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/poland...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/poland.png
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:32:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
2013/11/22 01:35:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "img".' in P:\home\blog.rt\YiiRoot\framework\web\CController.php:483
Stack trace:
#0 P:\home\blog.rt\YiiRoot\framework\web\CController.php(270): CController->missingAction('img')
#1 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(282): CController->run('img')
#2 P:\home\blog.rt\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/img.jp...')
#3 P:\home\blog.rt\YiiRoot\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 P:\home\blog.rt\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/img/img.jpg
HTTP_REFERER=http://blog.rt/index.php/site/page?view=about
---
